version: "3"
services:
  backend:
    build: backend
    container_name: st_backend
    networks:
      gateway:
      mongo:
        priority: 100
    depends_on:
      - keycloak
      - mongo
  frontend:
    build: frontend
    container_name: st_frontend
    networks:
      gateway:
    depends_on:
      - backend
  gateway:
    image: nginx
    container_name: st_gateway
    networks:
      gateway:
    depends_on:
      - backend
      - frontend
      - keycloak
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  keycloak:
    build: keycloak
    container_name: st_keycloak
    networks:
      gateway:
      postgres:
        priority: 100
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER:-admin}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD:-keycloak}
      - KEYCLOAK_FRONTEND_URL=${KEYCLOAK_FRONTEND_URL:-"http://localhost/auth/"}
      - DB_USER=${DB_USER:-keycloak}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_ADDR=${DB_ADDR:-postgres}
      - DB_DATABASE=${DB_DATABASE:-keycloak}
    depends_on:
      - postgres
  mongo:
    image: mongo
    container_name: st_mongo
    networks:
      mongo:
  postgres:
    image: postgres
    container_name: st_postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-keycloak}
      - POSTGRES_USER=${POSTGRES_USER:-keycloak}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    networks:
      postgres:
networks:
  gateway:
    name: st_gateway
  postgres:
    name: st_postgres
  mongo:
    name: st_mongo
